---

name: Sanity

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  rubocop:
    name: Ruby Linting
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'static/')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Rubocop
        run: gem install rubocop rubocop-performance rubocop-rails

      - name: Run Rubocop
        run: rubocop

  tests:
    name: Ruby Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-rubocop-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rails test
